# Generated by Django 2.2.11 on 2020-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug_name',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
